-- Seed data for rt_races (mirrors src/lib/db/seed.ts). Idempotent via on conflict.
-- Requires migrations 0001 and 0002.

insert into public.rt_races
  (id, name, date, distances, standard_distances, city, region, country, country_code, entry_status, is_major_marathon, is_major_qualifier, website, description, created_at)
values
  ('berlin-marathon-2026', 'Berlin Marathon', '2026-09-27', '[{"kind":"standard","distance":"Marathon"}]'::jsonb, array['Marathon']::text[], 'Berlin', 'Berlin', 'Germany', 'DE', 'ballot', true, true, 'https://www.bmw-berlin-marathon.com', 'Flat and fast World Marathon Major, home of multiple world records.', '2026-01-05T00:00:00.000Z'),
  ('chicago-marathon-2026', 'Chicago Marathon', '2026-10-11', '[{"kind":"standard","distance":"Marathon"}]'::jsonb, array['Marathon']::text[], 'Chicago', 'Illinois', 'United States', 'US', 'ballot', true, true, 'https://www.chicagomarathon.com', 'Fast, flat World Marathon Major through 29 neighborhoods.', '2026-01-05T00:00:00.000Z'),
  ('nyc-marathon-2026', 'New York City Marathon', '2026-11-01', '[{"kind":"standard","distance":"Marathon"}]'::jsonb, array['Marathon']::text[], 'New York', 'New York', 'United States', 'US', 'ballot', true, true, 'https://www.nyrr.org', 'The largest marathon in the world, through all five boroughs.', '2026-01-05T00:00:00.000Z'),
  ('valencia-marathon-2026', 'Valencia Marathon', '2026-12-06', '[{"kind":"standard","distance":"Marathon"},{"kind":"standard","distance":"10K"}]'::jsonb, array['Marathon', '10K']::text[], 'Valencia', 'Valencia', 'Spain', 'ES', 'open', false, true, 'https://www.valenciaciudaddelrunning.com', 'One of the fastest marathon courses in the world.', '2026-01-10T00:00:00.000Z'),
  ('boston-marathon-2027', 'Boston Marathon', '2027-04-19', '[{"kind":"standard","distance":"Marathon"}]'::jsonb, array['Marathon']::text[], 'Boston', 'Massachusetts', 'United States', 'US', 'closed', true, false, 'https://www.baa.org', 'The world''s oldest annual marathon. Qualifying time required.', '2026-02-01T00:00:00.000Z'),
  ('london-marathon-2027', 'London Marathon', '2027-04-25', '[{"kind":"standard","distance":"Marathon"}]'::jsonb, array['Marathon']::text[], 'London', 'Greater London', 'United Kingdom', 'GB', 'ballot', true, true, 'https://www.tcslondonmarathon.com', 'World Marathon Major from Greenwich to The Mall.', '2026-02-01T00:00:00.000Z'),
  ('great-north-run-2026', 'Great North Run', '2026-09-13', '[{"kind":"standard","distance":"Half Marathon"}]'::jsonb, array['Half Marathon']::text[], 'Newcastle upon Tyne', 'Tyne and Wear', 'United Kingdom', 'GB', 'ballot', false, false, 'https://www.greatrun.org', 'The world''s biggest half marathon, Newcastle to South Shields.', '2026-01-15T00:00:00.000Z'),
  ('park-to-pier-10k-2026', 'Park to Pier 10K', '2026-08-15', '[{"kind":"standard","distance":"10K"},{"kind":"standard","distance":"5K"}]'::jsonb, array['10K', '5K']::text[], 'Santa Monica', 'California', 'United States', 'US', 'open', false, false, null, 'Fast seaside out-and-back finishing on the pier.', '2026-03-01T00:00:00.000Z'),
  ('utmb-2026', 'Ultra-Trail du Mont-Blanc (UTMB)', '2026-08-28', '[{"kind":"custom","label":"171K mountain ultra","kilometers":171}]'::jsonb, array[]::text[], 'Chamonix', 'Auvergne-Rhône-Alpes', 'France', 'FR', 'ballot', false, false, 'https://utmb.world', 'Iconic mountain ultra circumnavigating Mont Blanc.', '2026-01-20T00:00:00.000Z'),
  ('western-states-2027', 'Western States Endurance Run', '2027-06-26', '[{"kind":"standard","distance":"100 Mile"}]'::jsonb, array['100 Mile']::text[], 'Olympic Valley', 'California', 'United States', 'US', 'ballot', false, false, 'https://www.wser.org', 'The world''s oldest 100-mile trail race, Olympic Valley to Auburn.', '2026-02-10T00:00:00.000Z'),
  ('sydney-marathon-2026', 'Sydney Marathon', '2026-08-30', '[{"kind":"standard","distance":"Marathon"},{"kind":"standard","distance":"Half Marathon"}]'::jsonb, array['Marathon', 'Half Marathon']::text[], 'Sydney', 'New South Wales', 'Australia', 'AU', 'open', true, true, 'https://www.sydneymarathon.com', 'The newest World Marathon Major, finishing at the Opera House.', '2026-01-25T00:00:00.000Z'),
  ('tokyo-marathon-2027', 'Tokyo Marathon', '2027-03-07', '[{"kind":"standard","distance":"Marathon"}]'::jsonb, array['Marathon']::text[], 'Tokyo', 'Tokyo', 'Japan', 'JP', 'ballot', true, true, 'https://www.marathon.tokyo', 'World Marathon Major through the heart of Tokyo.', '2026-02-15T00:00:00.000Z'),
  ('riverside-parkrun-classic-2026', 'Riverside Classic 5K', '2026-08-01', '[{"kind":"standard","distance":"5K"}]'::jsonb, array['5K']::text[], 'Austin', 'Texas', 'United States', 'US', 'open', false, false, null, 'Flat riverside 5K, chip timed, all abilities welcome.', '2026-04-01T00:00:00.000Z'),
  ('dublin-marathon-2026', 'Dublin Marathon', '2026-10-25', '[{"kind":"standard","distance":"Marathon"}]'::jsonb, array['Marathon']::text[], 'Dublin', 'Leinster', 'Ireland', 'IE', 'waitlist', false, true, 'https://www.dublinmarathon.ie', 'The friendly marathon — a lap of the city with huge crowds.', '2026-03-10T00:00:00.000Z'),
  ('two-oceans-2027', 'Two Oceans Marathon', '2027-03-27', '[{"kind":"custom","label":"56K ultra","kilometers":56},{"kind":"standard","distance":"Half Marathon"}]'::jsonb, array['Half Marathon']::text[], 'Cape Town', 'Western Cape', 'South Africa', 'ZA', 'open', false, false, 'https://www.twooceansmarathon.org.za', '"The world''s most beautiful marathon" around the Cape Peninsula.', '2026-04-05T00:00:00.000Z'),
  ('midnight-sun-half-2027', 'Midnight Sun Half Marathon', '2027-06-19', '[{"kind":"standard","distance":"Half Marathon"},{"kind":"standard","distance":"10K"}]'::jsonb, array['Half Marathon', '10K']::text[], 'Tromsø', 'Troms', 'Norway', 'NO', 'open', false, false, 'https://www.msm.no', 'Race under the midnight sun, north of the Arctic Circle.', '2026-05-01T00:00:00.000Z'),
  ('comrades-2027', 'Comrades Marathon', '2027-06-13', '[{"kind":"custom","label":"~88K road ultra","kilometers":88}]'::jsonb, array[]::text[], 'Durban', 'KwaZulu-Natal', 'South Africa', 'ZA', 'open', false, false, 'https://www.comrades.com', 'The world''s largest and oldest ultramarathon.', '2026-05-10T00:00:00.000Z'),
  ('manchester-marathon-2027', 'Manchester Marathon', '2027-04-11', '[{"kind":"standard","distance":"Marathon"}]'::jsonb, array['Marathon']::text[], 'Manchester', 'Greater Manchester', 'United Kingdom', 'GB', 'open', false, true, 'https://www.manchestermarathon.co.uk', 'The UK''s flattest, fastest big-city marathon.', '2026-05-15T00:00:00.000Z'),
  ('bay-bridge-backyard-2026', 'Bay Bridge Backyard Ultra', '2026-09-05', '[{"kind":"custom","label":"Backyard ultra (6.7K loops)","kilometers":6.7}]'::jsonb, array[]::text[], 'Oakland', 'California', 'United States', 'US', 'sold_out', false, false, null, 'Last one standing format — one 6.7K loop every hour.', '2026-04-20T00:00:00.000Z'),
  ('amsterdam-marathon-2026', 'Amsterdam Marathon', '2026-10-18', '[{"kind":"standard","distance":"Marathon"},{"kind":"standard","distance":"Half Marathon"}]'::jsonb, array['Marathon', 'Half Marathon']::text[], 'Amsterdam', 'North Holland', 'Netherlands', 'NL', 'open', false, true, 'https://www.tcsamsterdammarathon.nl', 'Fast autumn marathon finishing in the Olympic Stadium.', '2026-05-20T00:00:00.000Z'),
  ('vermont-50-2026', 'Vermont 50', '2026-09-27', '[{"kind":"standard","distance":"50 Mile"},{"kind":"standard","distance":"50K"}]'::jsonb, array['50 Mile', '50K']::text[], 'Brownsville', 'Vermont', 'United States', 'US', 'waitlist', false, false, null, 'Rolling trail ultra through Vermont fall foliage.', '2026-05-25T00:00:00.000Z'),
  ('lakeside-100k-2026', 'Lakeside 100K', '2026-11-14', '[{"kind":"standard","distance":"100K"}]'::jsonb, array['100K']::text[], 'Queenstown', 'Otago', 'New Zealand', 'NZ', 'open', false, false, null, 'Point-to-point 100K along Lake Wakatipu single track.', '2026-06-01T00:00:00.000Z'),
  ('invitational-elite-mile-2026', 'City Elite Mile', '2026-08-08', '[{"kind":"custom","label":"1 Mile road race","kilometers":1.609}]'::jsonb, array[]::text[], 'Eugene', 'Oregon', 'United States', 'US', 'invitation', false, false, null, 'Elite-only downtown road mile with world-class fields.', '2026-06-05T00:00:00.000Z'),
  ('paris-half-2027', 'Paris Half Marathon', '2027-03-07', '[{"kind":"standard","distance":"Half Marathon"}]'::jsonb, array['Half Marathon']::text[], 'Paris', 'Île-de-France', 'France', 'FR', 'open', false, false, 'https://www.harmoniemutuellesemideparis.com', 'Spring half through the heart of Paris.', '2026-06-10T00:00:00.000Z'),
  ('gold-coast-marathon-2027', 'Gold Coast Marathon', '2027-07-04', '[{"kind":"standard","distance":"Marathon"},{"kind":"standard","distance":"Half Marathon"},{"kind":"standard","distance":"10K"}]'::jsonb, array['Marathon', 'Half Marathon', '10K']::text[], 'Gold Coast', 'Queensland', 'Australia', 'AU', 'open', false, true, 'https://goldcoastmarathon.com.au', 'Flat, fast oceanside marathon — Australia''s premier road race.', '2026-06-15T00:00:00.000Z'),
  ('big-sur-2027', 'Big Sur International Marathon', '2027-04-25', '[{"kind":"standard","distance":"Marathon"},{"kind":"custom","label":"21-Miler","kilometers":33.8}]'::jsonb, array['Marathon']::text[], 'Big Sur', 'California', 'United States', 'US', 'ballot', false, false, 'https://www.bigsurmarathon.org', 'Highway 1 coastal scenery from Big Sur to Carmel.', '2026-06-20T00:00:00.000Z'),
  ('stockholm-marathon-2027', 'Stockholm Marathon', '2027-05-29', '[{"kind":"standard","distance":"Marathon"}]'::jsonb, array['Marathon']::text[], 'Stockholm', 'Stockholm', 'Sweden', 'SE', 'open', false, true, 'https://www.stockholmmarathon.se', 'Two-lap tour of Stockholm finishing in the 1912 Olympic Stadium.', '2026-06-25T00:00:00.000Z')
on conflict (id) do nothing;
