import type { Race } from "@/lib/types";

/**
 * Seed data for the in-memory store so the UI has something to show.
 * Dates are spread over the months following mid-2026.
 */
export const SEED_RACES: Race[] = [
  {
    id: "berlin-marathon-2026",
    name: "Berlin Marathon",
    date: "2026-09-27",
    distances: [{ kind: "standard", distance: "Marathon" }],
    city: "Berlin",
    region: "Berlin",
    country: "Germany",
    countryCode: "DE",
    entryStatus: "ballot",
    tags: ["World Major", "World Major Qualifier"],
    website: "https://www.bmw-berlin-marathon.com",
    description: "Flat and fast World Marathon Major, home of multiple world records.",
    createdAt: "2026-01-05T00:00:00.000Z",
  },
  {
    id: "chicago-marathon-2026",
    name: "Chicago Marathon",
    date: "2026-10-11",
    distances: [{ kind: "standard", distance: "Marathon" }],
    city: "Chicago",
    region: "Illinois",
    country: "United States",
    countryCode: "US",
    entryStatus: "ballot",
    tags: ["World Major", "World Major Qualifier"],
    website: "https://www.chicagomarathon.com",
    description: "Fast, flat World Marathon Major through 29 neighborhoods.",
    createdAt: "2026-01-05T00:00:00.000Z",
  },
  {
    id: "nyc-marathon-2026",
    name: "New York City Marathon",
    date: "2026-11-01",
    distances: [{ kind: "standard", distance: "Marathon" }],
    city: "New York",
    region: "New York",
    country: "United States",
    countryCode: "US",
    entryStatus: "ballot",
    tags: ["World Major", "World Major Qualifier"],
    website: "https://www.nyrr.org",
    description: "The largest marathon in the world, through all five boroughs.",
    createdAt: "2026-01-05T00:00:00.000Z",
  },
  {
    id: "valencia-marathon-2026",
    name: "Valencia Marathon",
    date: "2026-12-06",
    distances: [
      { kind: "standard", distance: "Marathon" },
      { kind: "standard", distance: "10K" },
    ],
    city: "Valencia",
    region: "Valencia",
    country: "Spain",
    countryCode: "ES",
    entryStatus: "open",
    tags: ["World Major Qualifier"],
    website: "https://www.valenciaciudaddelrunning.com",
    description: "One of the fastest marathon courses in the world.",
    createdAt: "2026-01-10T00:00:00.000Z",
  },
  {
    id: "boston-marathon-2027",
    name: "Boston Marathon",
    date: "2027-04-19",
    distances: [{ kind: "standard", distance: "Marathon" }],
    city: "Boston",
    region: "Massachusetts",
    country: "United States",
    countryCode: "US",
    entryStatus: "closed",
    tags: ["World Major"],
    website: "https://www.baa.org",
    description: "The world's oldest annual marathon. Qualifying time required.",
    createdAt: "2026-02-01T00:00:00.000Z",
  },
  {
    id: "london-marathon-2027",
    name: "London Marathon",
    date: "2027-04-25",
    distances: [{ kind: "standard", distance: "Marathon" }],
    city: "London",
    region: "Greater London",
    country: "United Kingdom",
    countryCode: "GB",
    entryStatus: "ballot",
    tags: ["World Major", "World Major Qualifier"],
    website: "https://www.tcslondonmarathon.com",
    description: "World Marathon Major from Greenwich to The Mall.",
    createdAt: "2026-02-01T00:00:00.000Z",
  },
  {
    id: "great-north-run-2026",
    name: "Great North Run",
    date: "2026-09-13",
    distances: [{ kind: "standard", distance: "Half Marathon" }],
    city: "Newcastle upon Tyne",
    region: "Tyne and Wear",
    country: "United Kingdom",
    countryCode: "GB",
    entryStatus: "ballot",
    tags: [],
    website: "https://www.greatrun.org",
    description: "The world's biggest half marathon, Newcastle to South Shields.",
    createdAt: "2026-01-15T00:00:00.000Z",
  },
  {
    id: "park-to-pier-10k-2026",
    name: "Park to Pier 10K",
    date: "2026-08-15",
    distances: [
      { kind: "standard", distance: "10K" },
      { kind: "standard", distance: "5K" },
    ],
    city: "Santa Monica",
    region: "California",
    country: "United States",
    countryCode: "US",
    entryStatus: "open",
    tags: [],
    description: "Fast seaside out-and-back finishing on the pier.",
    createdAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "utmb-2026",
    name: "Ultra-Trail du Mont-Blanc (UTMB)",
    date: "2026-08-28",
    distances: [{ kind: "custom", label: "171K mountain ultra", kilometers: 171 }],
    city: "Chamonix",
    region: "Auvergne-Rhône-Alpes",
    country: "France",
    countryCode: "FR",
    entryStatus: "ballot",
    tags: [],
    website: "https://utmb.world",
    description: "Iconic mountain ultra circumnavigating Mont Blanc.",
    createdAt: "2026-01-20T00:00:00.000Z",
  },
  {
    id: "western-states-2027",
    name: "Western States Endurance Run",
    date: "2027-06-26",
    distances: [{ kind: "standard", distance: "100 Mile" }],
    city: "Olympic Valley",
    region: "California",
    country: "United States",
    countryCode: "US",
    entryStatus: "ballot",
    tags: [],
    website: "https://www.wser.org",
    description: "The world's oldest 100-mile trail race, Olympic Valley to Auburn.",
    createdAt: "2026-02-10T00:00:00.000Z",
  },
  {
    id: "sydney-marathon-2026",
    name: "Sydney Marathon",
    date: "2026-08-30",
    distances: [
      { kind: "standard", distance: "Marathon" },
      { kind: "standard", distance: "Half Marathon" },
    ],
    city: "Sydney",
    region: "New South Wales",
    country: "Australia",
    countryCode: "AU",
    entryStatus: "open",
    tags: ["World Major", "World Major Qualifier"],
    website: "https://www.sydneymarathon.com",
    description: "The newest World Marathon Major, finishing at the Opera House.",
    createdAt: "2026-01-25T00:00:00.000Z",
  },
  {
    id: "tokyo-marathon-2027",
    name: "Tokyo Marathon",
    date: "2027-03-07",
    distances: [{ kind: "standard", distance: "Marathon" }],
    city: "Tokyo",
    region: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    entryStatus: "ballot",
    tags: ["World Major", "World Major Qualifier"],
    website: "https://www.marathon.tokyo",
    description: "World Marathon Major through the heart of Tokyo.",
    createdAt: "2026-02-15T00:00:00.000Z",
  },
  {
    id: "riverside-parkrun-classic-2026",
    name: "Riverside Classic 5K",
    date: "2026-08-01",
    distances: [{ kind: "standard", distance: "5K" }],
    city: "Austin",
    region: "Texas",
    country: "United States",
    countryCode: "US",
    entryStatus: "open",
    tags: [],
    description: "Flat riverside 5K, chip timed, all abilities welcome.",
    createdAt: "2026-04-01T00:00:00.000Z",
  },
  {
    id: "dublin-marathon-2026",
    name: "Dublin Marathon",
    date: "2026-10-25",
    distances: [{ kind: "standard", distance: "Marathon" }],
    city: "Dublin",
    region: "Leinster",
    country: "Ireland",
    countryCode: "IE",
    entryStatus: "waitlist",
    tags: ["World Major Qualifier"],
    website: "https://www.dublinmarathon.ie",
    description: "The friendly marathon — a lap of the city with huge crowds.",
    createdAt: "2026-03-10T00:00:00.000Z",
  },
  {
    id: "two-oceans-2027",
    name: "Two Oceans Marathon",
    date: "2027-03-27",
    distances: [
      { kind: "custom", label: "56K ultra", kilometers: 56 },
      { kind: "standard", distance: "Half Marathon" },
    ],
    city: "Cape Town",
    region: "Western Cape",
    country: "South Africa",
    countryCode: "ZA",
    entryStatus: "open",
    tags: [],
    website: "https://www.twooceansmarathon.org.za",
    description: "\"The world's most beautiful marathon\" around the Cape Peninsula.",
    createdAt: "2026-04-05T00:00:00.000Z",
  },
  {
    id: "midnight-sun-half-2027",
    name: "Midnight Sun Half Marathon",
    date: "2027-06-19",
    distances: [
      { kind: "standard", distance: "Half Marathon" },
      { kind: "standard", distance: "10K" },
    ],
    city: "Tromsø",
    region: "Troms",
    country: "Norway",
    countryCode: "NO",
    entryStatus: "open",
    tags: [],
    website: "https://www.msm.no",
    description: "Race under the midnight sun, north of the Arctic Circle.",
    createdAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "comrades-2027",
    name: "Comrades Marathon",
    date: "2027-06-13",
    distances: [{ kind: "custom", label: "~88K road ultra", kilometers: 88 }],
    city: "Durban",
    region: "KwaZulu-Natal",
    country: "South Africa",
    countryCode: "ZA",
    entryStatus: "open",
    tags: [],
    website: "https://www.comrades.com",
    description: "The world's largest and oldest ultramarathon.",
    createdAt: "2026-05-10T00:00:00.000Z",
  },
  {
    id: "manchester-marathon-2027",
    name: "Manchester Marathon",
    date: "2027-04-11",
    distances: [{ kind: "standard", distance: "Marathon" }],
    city: "Manchester",
    region: "Greater Manchester",
    country: "United Kingdom",
    countryCode: "GB",
    entryStatus: "open",
    tags: ["World Major Qualifier"],
    website: "https://www.manchestermarathon.co.uk",
    description: "The UK's flattest, fastest big-city marathon.",
    createdAt: "2026-05-15T00:00:00.000Z",
  },
  {
    id: "bay-bridge-backyard-2026",
    name: "Bay Bridge Backyard Ultra",
    date: "2026-09-05",
    distances: [
      { kind: "custom", label: "Backyard ultra (6.7K loops)", kilometers: 6.7 },
    ],
    city: "Oakland",
    region: "California",
    country: "United States",
    countryCode: "US",
    entryStatus: "sold_out",
    tags: [],
    description: "Last one standing format — one 6.7K loop every hour.",
    createdAt: "2026-04-20T00:00:00.000Z",
  },
  {
    id: "amsterdam-marathon-2026",
    name: "Amsterdam Marathon",
    date: "2026-10-18",
    distances: [
      { kind: "standard", distance: "Marathon" },
      { kind: "standard", distance: "Half Marathon" },
    ],
    city: "Amsterdam",
    region: "North Holland",
    country: "Netherlands",
    countryCode: "NL",
    entryStatus: "open",
    tags: ["World Major Qualifier"],
    website: "https://www.tcsamsterdammarathon.nl",
    description: "Fast autumn marathon finishing in the Olympic Stadium.",
    createdAt: "2026-05-20T00:00:00.000Z",
  },
  {
    id: "vermont-50-2026",
    name: "Vermont 50",
    date: "2026-09-27",
    distances: [
      { kind: "standard", distance: "50 Mile" },
      { kind: "standard", distance: "50K" },
    ],
    city: "Brownsville",
    region: "Vermont",
    country: "United States",
    countryCode: "US",
    entryStatus: "waitlist",
    tags: [],
    description: "Rolling trail ultra through Vermont fall foliage.",
    createdAt: "2026-05-25T00:00:00.000Z",
  },
  {
    id: "lakeside-100k-2026",
    name: "Lakeside 100K",
    date: "2026-11-14",
    distances: [{ kind: "standard", distance: "100K" }],
    city: "Queenstown",
    region: "Otago",
    country: "New Zealand",
    countryCode: "NZ",
    entryStatus: "open",
    tags: [],
    description: "Point-to-point 100K along Lake Wakatipu single track.",
    createdAt: "2026-06-01T00:00:00.000Z",
  },
  {
    id: "invitational-elite-mile-2026",
    name: "City Elite Mile",
    date: "2026-08-08",
    distances: [{ kind: "custom", label: "1 Mile road race", kilometers: 1.609 }],
    city: "Eugene",
    region: "Oregon",
    country: "United States",
    countryCode: "US",
    entryStatus: "invitation",
    tags: [],
    description: "Elite-only downtown road mile with world-class fields.",
    createdAt: "2026-06-05T00:00:00.000Z",
  },
  {
    id: "paris-half-2027",
    name: "Paris Half Marathon",
    date: "2027-03-07",
    distances: [{ kind: "standard", distance: "Half Marathon" }],
    city: "Paris",
    region: "Île-de-France",
    country: "France",
    countryCode: "FR",
    entryStatus: "open",
    tags: [],
    website: "https://www.harmoniemutuellesemideparis.com",
    description: "Spring half through the heart of Paris.",
    createdAt: "2026-06-10T00:00:00.000Z",
  },
  {
    id: "gold-coast-marathon-2027",
    name: "Gold Coast Marathon",
    date: "2027-07-04",
    distances: [
      { kind: "standard", distance: "Marathon" },
      { kind: "standard", distance: "Half Marathon" },
      { kind: "standard", distance: "10K" },
    ],
    city: "Gold Coast",
    region: "Queensland",
    country: "Australia",
    countryCode: "AU",
    entryStatus: "open",
    tags: ["World Major Qualifier"],
    website: "https://goldcoastmarathon.com.au",
    description: "Flat, fast oceanside marathon — Australia's premier road race.",
    createdAt: "2026-06-15T00:00:00.000Z",
  },
  {
    id: "big-sur-2027",
    name: "Big Sur International Marathon",
    date: "2027-04-25",
    distances: [
      { kind: "standard", distance: "Marathon" },
      { kind: "custom", label: "21-Miler", kilometers: 33.8 },
    ],
    city: "Big Sur",
    region: "California",
    country: "United States",
    countryCode: "US",
    entryStatus: "ballot",
    tags: [],
    website: "https://www.bigsurmarathon.org",
    description: "Highway 1 coastal scenery from Big Sur to Carmel.",
    createdAt: "2026-06-20T00:00:00.000Z",
  },
  {
    id: "stockholm-marathon-2027",
    name: "Stockholm Marathon",
    date: "2027-05-29",
    distances: [{ kind: "standard", distance: "Marathon" }],
    city: "Stockholm",
    region: "Stockholm",
    country: "Sweden",
    countryCode: "SE",
    entryStatus: "open",
    tags: ["World Major Qualifier"],
    website: "https://www.stockholmmarathon.se",
    description: "Two-lap tour of Stockholm finishing in the 1912 Olympic Stadium.",
    createdAt: "2026-06-25T00:00:00.000Z",
  },
];
